<div
        id="vue-app"
        class="page-app layout layout--default"
>
    <pre>
        <code>
            @php
                print_r($language);
                print_r($page);
                print_r($detail);
            @endphp
        </code>
    </pre>
    @include('shared.header')
    <div>
        <div>
            @include($page['template'])
        </div>
        @include('shared.sidebar')
    </div>
    @include('shared.footer')
</div>