<div
        id="vue-app"
        class="page-app layout layout--minimal"
>
    <pre>
        <code>
            @php
                print_r($language);
                print_r($page);
                print_r($detail);
                print_r($_page);
                print_r($_category);
                print_r($_detail);
            @endphp
        </code>
    </pre>
    <div>
        @include($page['template'])
    </div>
    @include('shared.footer')
</div>