export const APP_LANGUAGE_TOGGLE = 'APP_LANGUAGE_TOGGLE';
export const APP_THEME_TOGGLE = 'APP_THEME_TOGGLE';
export const APP_SIDEBAR_TOGGLE = 'APP_SIDEBAR_TOGGLE';
export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';
