import { CategoriesItemModel, CategoriesItemLangModel } from './Categories';
import { CommentsItemModel } from './Comments';
import { MembersItemModel } from './Members';
import { MenuItemModel } from './Menu';
import { MenuItemsItemModel } from './MenuItems';
import { PagesItemModel, PagesItemLangModel } from './Pages';
import { PostsItemModel, PostsItemLangModel } from './Posts';
import { TagsItemModel } from './Tags';
import { TranslationsItemLangModel, TranslationsItemModel } from './Translations';
import { UsersItemModel } from './Users';
import { UploadsItemModel, UploadsItemLangModel } from './Uploads';
import { MessagesItemModel } from './Messages';

export type CategoriesItemProps = CategoriesItemModel;
export type CategoriesItemLangProps = CategoriesItemLangModel;
export type CommentsItemProps = CommentsItemModel;
export type MembersItemProps = MembersItemModel;
export type MenuItemProps = MenuItemModel;
export type MenuItemsItemProps = MenuItemsItemModel;
export type PagesItemProps = PagesItemModel;
export type PagesItemLangProps = PagesItemLangModel;
export type PostsItemProps = PostsItemModel;
export type PostsItemLangProps = PostsItemLangModel;
export type TagsItemProps = TagsItemModel;
export type TranslationsItemProps = TranslationsItemModel;
export type TranslationsItemLangProps = TranslationsItemLangModel;
export type UsersItemProps = UsersItemModel;
export type UploadsItemProps = UploadsItemModel;
export type UploadsItemLangProps = UploadsItemLangModel;
export type MessagesItemProps = MessagesItemModel;
