import { routesProps } from './types/page';

export default {
	error: {
		path: null,
		key: 'error',
		title: 'error.meta_title',
		auth: 0,
	},
	login: {
		path: 'login',
		key: 'login',
		label: 'login.label',
		title: 'login.meta_title',
		auth: 0,
	},
	lostPassword: {
		path: 'lost-password',
		key: 'lostPassword',
		label: 'lostPassword.label',
		title: 'lostPassword.meta_title',
		auth: 0,
	},
	dashboard: {
		path: '',
		key: 'dashboard',
		label: 'dashboard.label',
		title: 'dashboard.meta_title',
		auth: 3,
	},
	settings: {
		path: 'settings',
		key: 'settings',
		label: 'settings.label',
		title: 'settings.meta_title',
		auth: 7,
	},
	categories: {
		path: 'categories',
		key: 'categories',
		label: 'categories.label',
		title: 'categories.meta_title',
		auth: 3,
	},
	members: {
		path: 'members',
		key: 'members',
		label: 'members.label',
		title: 'members.meta_title',
		auth: 5,
	},
	menu: {
		path: 'menu',
		key: 'menu',
		label: 'menu.label',
		title: 'menu.meta_title',
		auth: 5,
	},
	pages: {
		path: 'pages',
		key: 'pages',
		label: 'pages.label',
		title: 'pages.meta_title',
		auth: 5,
	},
	posts: {
		path: 'posts',
		key: 'posts',
		label: 'posts.label',
		title: 'posts.meta_title',
		auth: 3,
	},
	tags: {
		path: 'tags',
		key: 'tags',
		label: 'tags.label',
		title: 'tags.meta_title',
		auth: 3,
	},
	translations: {
		path: 'translations',
		key: 'translations',
		label: 'translations.label',
		title: 'translations.meta_title',
		auth: 5,
	},
	uploads: {
		path: 'uploads',
		key: 'uploads',
		label: 'uploads.label',
		title: 'uploads.meta_title',
		auth: 3,
	},
	users: {
		path: 'users',
		key: 'users',
		label: 'users.label',
		title: 'users.meta_title',
		auth: 7,
	},
} as routesProps;