import { MembersItemProps } from '../../types/model';

export default {
	id: 'new',
	type: 'default',
	email: '',
	phone: '',
	name_first: '',
	name_last: '',
	nickname: '',
	password: '',
	position: '',
	address: '',
	city: '',
	country: '',
	zip: '',
	item_group: 'unknown',
	img_avatar: '',
	phone_alt: [],
	email_alt: [],
	sex: 'undefined',
	birthdate: null,
	description: '',
	subscription: false,
	active: true,
} as MembersItemProps;
